name: CI

on:
    push:
      branches:
        - master
      tags:
        - "v**"

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4.1.1
              with:
                  ref: 'master'

            - name: Setup Python
              uses: actions/setup-python@v4.7.1
              with:
                python-version: '3.11'

            - name: Build exe
              run: |
                pip install -U nuitka
                pip install -r requirements.txt
                nuitka --windows-disable-console --standalone --enable-plugins=pyside6 --assume-yes-for-downloads --main=src\main.py --main=src\update.py --output-dir=output
                nuitka --windows-disable-console --standalone --enable-plugins=pyside6 --assume-yes-for-downloads src\main.py
                nuitka --windows-disable-console --standalone --enable-plugins=pyside6 --assume-yes-for-downloads src\update.py
                rm output\main.dist\main.exe
                cp main.dist\main.exe output\main.dist
                cp update.dist\update.exe output\main.dist

            - name: GH Release
              uses: softprops/action-gh-release@v0.1.15
              with:
                name: Autorelease
                prerelease: true
                body_path: changes.txt
                files: bin\Debug\zh-CN\Wosea.msi