name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build "main.exe"
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.12'
          spec: 'src\main.py'
          requirements: '.\requirements.txt'
          options: --name "main",--onefile,--windowed
      - name: Move file 1
        run: |
          mkdir output
          mv .\dist\main.exe .\output\
      - name: Build "update.exe"
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.12'
          spec: 'src\update.py'
          requirements: '.\requirements.txt'
          options: --onefile,--windowed
      - name: Move file 2
        run: |
          mv .\dist\update.exe .\output
      - name: Build "Setup.exe"
        uses: Minionguyjpro/Inno-Setup-Action@v1.0.0
        with:
          path: .\build.iss